### PR TITLE
Fieldset polygon visualization

### PR DESCRIPTION
**Pull request by joshlfriesen**
Switched fieldset visualization from a  laser_scan to polygon. It is more visually intuitive.
[Screencast from 06-18-2024 02:45:14 PM.webm](https://github.com/locusrobotics/sick_safetyscanners/assets/144175590/5c0adbfb-7982-4b9f-b7e8-c360bee9025d)

[Screencast from 06-18-2024 03:09:39 PM.webm](https://github.com/locusrobotics/sick_safetyscanners/assets/144175590/f2cc648b-db93-4824-b86c-9a3c949622c0)

### CODE REVIEW

**Comment by joshlfriesen** [comment]
Also Josh - I'll play around with colors, etc. for the polygons, but I'm going to do that in locus_viz

**Review by nickovaras — APPROVED** [review]
Looks good. I wonder if there's easily available functions to reduce the point count of a polygon, as many of the straight edges are defined with a couple points.

**Comment by nickovaras** [comment]
Something like this: (Douglas-Peucker) . https://dyn4j.org/2021/06/2021-06-10-simple-polygon-simplification/
Especially considering that the fields are not changing, so we'd only have to compute this once when the field is received for the first time, then we store it and publish it without all the extra points.

**Review by jwallace42 — COMMENTED** [review]
Looks good! 

There two things that I think are important to have. 

A video where we trigger dtz or protective stop. It would be great to see the polygon change color when we trigger any sort of throttling. 

I think it would be great to add the field that the lidars are operating in as some text.

**Comment by joshlfriesen** [comment]
Made Josh's updates. Safety field being intruded:
Screenshot from 2024-06-19 16-16-19

Regular vid (laggy from connection):
[Screencast from 06-19-2024 02:05:34 PM.webm](https://github.com/locusrobotics/sick_safetyscanners/assets/144175590/246ac2a3-0252-4b4b-aa9c-47794ed36b94)

**Review by jwallace42 — APPROVED** [review]

**Pull request merged**
